# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [17]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    sigmoid = 1/(1+np.exp(-x))
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([[0],[0],[1],[1]])


In [18]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) - 1
# define syn1
syn1 = 0.5*np.random.random((4,1)) 

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）



神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [19]:
for iter in range(100000):
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    

  # l2_error 該值說明了神經網路預測時“丟失”的數目。     
  # l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。   

  # l1_error 該值為 l2_delta 經 syn1 加權後的結果，從而能夠計算得到中間層/隱層的誤差。   
  # l1_delta 該值為經確信度加權後的神經網路 l1 層的誤差，除了確信誤差很小時，它近似等於 l1_error 。

    l2_error = y - l2
    if iter %10000 ==0:
      print(f"第{iter}層，誤差為 \n{l2_error}")
    l2_delta = l2_error * nonlin(l2,True)

    # how much did we miss?
    l1_error = l2_delta.dot(syn1.T)
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    # update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
     # syn1 update weights
    
print("Output After Training:")
print(l1)
print("\n\n")
print(l2)

第0層，誤差為 
[[-0.61739576]
 [-0.58622197]
 [ 0.38091238]
 [ 0.4121801 ]]
第10000層，誤差為 
[[-0.00491818]
 [-0.00434044]
 [ 0.00546881]
 [ 0.00563926]]
第20000層，誤差為 
[[-0.00337595]
 [-0.003003  ]
 [ 0.00380412]
 [ 0.00391926]]
第30000層，誤差為 
[[-0.0027146 ]
 [-0.00242413]
 [ 0.00308133]
 [ 0.00317367]]
第40000層，誤差為 
[[-0.00232729]
 [-0.00208339]
 [ 0.00265492]
 [ 0.00273415]]
第50000層，誤差為 
[[-0.00206614]
 [-0.00185284]
 [ 0.00236591]
 [ 0.0024364 ]]
第60000層，誤差為 
[[-0.0018751 ]
 [-0.00168375]
 [ 0.00215364]
 [ 0.00221778]]
第70000層，誤差為 
[[-0.00172768]
 [-0.00155301]
 [ 0.00198931]
 [ 0.00204856]]
第80000層，誤差為 
[[-0.00160955]
 [-0.00144807]
 [ 0.00185727]
 [ 0.00191262]]
第90000層，誤差為 
[[-0.00151219]
 [-0.00136146]
 [ 0.00174818]
 [ 0.00180033]]
Output After Training:
[[0.49694552 0.14786661 0.87004757 0.67038522]
 [0.33906458 0.09848114 0.88085957 0.61818249]
 [0.18429672 0.96116515 0.05058102 0.13352067]
 [0.10501055 0.93968959 0.0555637  0.10926519]]



[[0.0014302 ]
 [0.00128843]
 [0.99834388]
 [0.998